version: "2.1"

services:
  app:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    image: go_fast_server
    restart: always
    networks:
      - go_fast_web
      - default
    command: /go-fast
    labels:
      - "traefik.frontend.rule=Host:app.docker.localhost"
      - "traefik.docker.network=go_fast_web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:go-fast.djangulo.com"
      - "traefik.basic.port=9000"
      - "traefik.basic.protocol=http"
      - "traefik.admin.frontend.rule=Host:admin-go-fast.djangulo.com"
      - "traefik.admin.protocol=https"
      - "traefik.admin.port=9443"
  traefik:
    image: traefik:<stable version from https://hub.docker.com/_/traefik>
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - go_fast_web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deployments/traefik/traefik.toml:/traefik.toml
      - ./deployments/traefik/acme.json:/acme.json
    container_name: traefik

networks:
  go_fast_web:
    external: true
