version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./deployments/local/go/Dockerfile
    image: go_fast_local
    command: ['/wait-for', 'postgres:5432', '--', '/webserver', '-p', '9000']
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '9000:9000'

  postgres:
    build:
      context: .
      dockerfile: ./deployments/production/postgres/Dockerfile
    healthcheck:
      test: ['CMD', 'sh', '-c', '/usr/local/bin/healthcheck']
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s
    image: go_fast_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

volumes:
  local_postgres_data: {}
  local_postgres_backups: {}
