version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./deployments/production/go/Dockerfile
    image: go_fast_production_app
    restart: always
    command: ['/wait-for', 'postgres:5432', '--', '/webserver', '-p', '10000']
    depends_on:
      - postgres
    env_file:
      - ./.envs/.production/.postgres
    expose:
      - '10000'
    networks:
      - go_fast_production
      - default
    labels:
      - 'traefik.docker.network=go_fast_production'
      - 'traefik.enable=true'
      - 'traefik.basic.frontend.rule=Host:go-fast.djangulo.com'
      - 'traefik.basic.port=10000'
      - 'traefik.basic.protocol=http'

  postgres:
    build:
      context: .
      dockerfile: ./deployments/production/postgres/Dockerfile
    healthcheck:
      test: ['CMD', 'sh', '-c', '/usr/local/bin/healthcheck']
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    image: go_fast_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

volumes:
  production_postgres_data: {}
  production_postgres_backups: {}

networks:
  go_fast_production:
    external: true
