version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./deployments/production/go/Dockerfile
    image: go_fast_production_app
    restart: always
    command: /start
    expose:
      - '10000'
    networks:
      - go_fast_production
      - default
    labels:
      - 'traefik.docker.network=go_fast_production'
      - 'traefik.enable=true'
      - 'traefik.basic.frontend.rule=Host:go-fast.djangulo.com'
      - 'traefik.basic.port=10000'
      - 'traefik.basic.protocol=http'

networks:
  go_fast_production:
    external: true
