version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./deployments/production/go/Dockerfile
    image: go_fast_production_app
    restart: always
    command: /root/webserver -p 10000
    expose:
      - "10000"
    networks:
      - go_fast_production
      - default
    labels:
      - "traefik.docker.network=go_fast_production"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:go-fast.djangulo.com"
      - "traefik.basic.port=10000"
      - "traefik.basic.protocol=http"
      - "traefik.admin.frontend.rule=Host:go-fast-admin.djangulo.com"
      - "traefik.admin.protocol=https"
      - "traefik.admin.port=9443"
      - "traefik.admin.frontend.auth.basic.users=djangulo:$$apr1$$h.wPwHEW$$yEgYhPyNr4sn8dy4Nbbs70"

networks:
  go_fast_production:
    external: true
