version: "3"

services:
  staging_app:
    build:
      context: .
      dockerfile: ./deployments/staging/go/Dockerfile
    image: go_fast_staging_app
    restart: always
    command: /root/webserver -p 9000
    expose:
      - "9000"
    networks:
      - go_fast_staging
      - default
    labels:
      - "traefik.docker.network=go_fast_staging"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:go-fast-staging.djangulo.com"
      - "traefik.basic.port=9000"
      - "traefik.basic.protocol=http"
      - "traefik.admin.frontend.rule=Host:go-fast-staging-admin.djangulo.com"
      - "traefik.admin.protocol=https"
      - "traefik.admin.port=9443"
      - "traefik.admin.frontend.auth.basic.users=djangulo:$$apr1$$h.wPwHEW$$yEgYhPyNr4sn8dy4Nbbs70"

networks:
  go_fast_staging:
    external: true
