version: '2'

services:
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/djangulo/go/src/github.com/djangulo/go-fast/traefik/traefik.toml:/traefik.toml
      - /home/djangulo/go/src/github.com/djangulo/go-fast/traefik/acme.json:/acme.json
    container_name: traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=Host:admin.DOCKER_DOMAIN' # <---- admin
      - 'traefik.port=8080'
      - 'traefik.backend.healthcheck.interval=10s'

networks:
