debug = false

loglevel = "INFO"
defaultEntryPoints = ["https", "http"]

# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  # https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[file]
[backends]
  [backends.gofast]
    [backends.gofast.servers.server1]
      url = "http://go-fast:5000"

[frontends]
  [frontends.gofast]
    backend = "gofast"
    passHostHeader = true
    [frontends.gofast.headers]
      HostsProxyHeaders = ['X-CSRFToken']
    [frontends.django.routes.dr1]
      rule = "Host:go-fast.djangulo.com"

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
# Email address used for registration
email = "djal@tuto.io"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onDemand = false
OnHostRule = true
  # Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
  [acme.httpChallenge]
  entryPoint = "http"