#!/usr/bin/env bash


# set -o errexit
set -o pipefail
# set -o nounset

working_dir="$(dirname ${0})"
source "${working_dir}/_sourced/messages.sh"
source "${working_dir}/_sourced/constants.sh"

show_help(){
cat << EOF
Usage: traefikinit [OPTIONS]
     
Initial setup for traefik with docker"
Creates traefik scaffolding under <traefik-root>/<project-name>
then starts a service as described in ./traefik-compose.yml"
    
    -h, --help              show this help message and exit
    -t, --traefik-root      root dir for traefik, default /opt/traefik
    -p, --project-name      dirname for project traefik files
    -a, --admin             email address to register the acme challenges against
    -u, --docker-domain     domain to assign to the docker provider on traefik.toml
    -n, --networks          comma separated list of networks to insert in traefik
                            compose file, these networks need to be added manually
                            to your own docker compose
    -d, --dry-run           flag to run without making any changes

EOF
echo -e ${SCRIPT_WARNING}
}

if ! docker_loc="$(type -p "docker")" || [[ -z $docker_loc ]]; then
    message_error ${DOCKER_REQUIRED}
    exit 1
fi

if ! compose_loc="$(type -p "docker-compose")" || [[ -z $compose_loc ]]; then
    message_error "${DOCKER_REQUIRED//docker/docker-compose}, installing docker-compose"
    sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
fi

message_warning ${SCRIPT_WARNING}

while [ "$1" != "" ]; do
    case $1 in
        -p|--project-name)  pname="$2"; shift;;
        -t|--traefik-root)  troot="$2"; shift;;
        -u|--docker-domain) host="$2"; shift;;
        -a|--admin)         admin="$2"; shift;;
        -d|--dry-run)       dryrun="$2"; shift;;
        -n|--networks)   networks="$2"; shift;;
        -h|-\?|--help)      show_help; exit;;
        -*|--*=)            message_error "Unsuported arg $2"; show_help; exit 1;;
        *)               # Default case: No more options, so break out of the loop.
    esac
    shift
done

if [[ -z "${dryrun}" ]]; then
    dryrun=false
else
    message_info "Performing dry run"
fi

if [[ -z "${pname}" ]]; then
    pname="$(basename $(dirname $(dirname $(dirname `pwd`))))"
    message_info "project-name not set, defaulting to: ${pname}"
else
    message_info "project-name: ${pname}"
fi

snake_pname=${pname//[- .]/_}
kebab_pname=${pname//[- .]/-}

if [[ -z "${troot}" ]]; then
    troot=/opt/traefik
    message_info "traefik-root [dir] not set, defaulting to: ${troot}"
else
    message_info "traefik-root: ${troot}"
fi

if [[ -z "${networks}" ]]; then
    networks="${snake_pname}_web"
    message_info "no --networks passed in, defaulting to: ${snake_pname}_web"
    split_net="${snake_pname}_web"
else
    message_info "networks: ${networks}"
    split_net=$(echo $networks | tr "," "\n")
fi

traefik_path="${troot}"/"${snake_pname}"
if [ ! -d $troot ]; then
    message_info "$troot does not exist, creating dir $traefik_path"
    if [ "$dryrun" = false ]; then
        mkdir -p "${traefik_path}"
    fi
else
    if [ ! -d $traefik_path ]; then
        message_info "$troot dir exists, creating dir $traefik_path"
        if [ "$dryrun" = false ]; then
            mkdir -p "${traefik_path}"
        fi
    else
        message_info "$traefik_path dir exists, no changes"
    fi
fi

if [[ -z "${host}" ]]; then
    message_warning "--docker-domain not set, you will need to make manual changes to ${traefik_path}/traefik.toml"
else
    message_info "docker domain: ${host}"
fi

if [[ -z "${admin}" ]]; then
    message_warning "--admin not set, you will need to make manual changes to ${traefik_path}/traefik.toml"
else
    message_info "admin email: ${admin}"
fi

if [ -f "$traefik_path/traefik.toml" ]; then
    message_info "$traefik_path/traefik.toml found, leaving uchanged"
else
    if [ "$dryrun" = false ]; then
        message_info "Copying $working_dir/traefik.toml => $traefik_path/traefik.toml"
        cp $working_dir/traefik.toml $traefik_path/traefik.toml
        sed -i 's/\r//g' $traefik_path/traefik.toml
        if [[ ! -z "${admin}" ]]; then
            message_info "Setting $traefik_path/traefik.toml admin = $admin"
            sed -i "s/ADMIN_EMAIL/${admin}/g" $traefik_path/traefik.toml
        fi
        if [[ ! -z "${host}" ]]; then
        message_info "Setting $traefik_path/traefik.toml docker domain = $host"
            sed -i "s#\"DOCKER_DOMAIN\"#\"${host}\"#g" $traefik_path/traefik.toml
        fi
    fi
fi

if [ -f "$traefik_path/acme.json" ]; then
    message_info "$traefik_path/acme.json found, leaving uchanged"
else
    if [ "$dryrun" = false ]; then
        message_info "Creating blank $traefik_path/acme.json"
        touch $traefik_path/acme.json
        chmod 600 $traefik_path/acme.json
    fi
fi

if [ -f "$traefik_path/docker-compose.yaml" ]; then
    message_info "$traefik_path/docker-compose.yaml found, leaving uchanged"
else
    if [ "$dryrun" = false ]; then
        message_info "Copying $working_dir/docker-compose.yml => $traefik_path/docker-compose.yml"
        cp $working_dir/docker-compose.yml $traefik_path/docker-compose.yml
        sed -i 's/\r//g' $traefik_path/docker-compose.yml
    fi
fi

message_success "Traefik-docker scaffolding created succesfully"
if ! tree_loc="$(type -p "tree")" || [[ -z $tree_loc ]]; then
    ls -la ${traefik_path}
else
    tree ${traefik_path}
fi



if [[ -z "${networks}" ]]; then
    $working_dir/insert_network -i $split_net "$traefik_path/docker-compose.yml"
else
    for network in $split_net
    do
        if [ "$dryrun" = false ]; then
            $working_dir/insert_network -i $network "$traefik_path/docker-compose.yml"
        else
            $working_dir/insert_network $network "$traefik_path/docker-compose.yml"
        fi
    done
fi

# message_info "Creating networks as  \e[33m${snake_pname}_web\e[0m"
# echo -e "\tdocker network create ${snake_pname}_web"
# network_create_output=$(docker network create "${snake_pname}_web" 2>&1 | tr -d '\r')
# if [ ${network_create_output:0:5} == "Error" ] || [[ -z "${network_create_output}" ]]; then
#     message_error "$network_create_output"
#     exit 1
# else
#     message_success "Network \e[33m${snake_pname}_web\e[0m created succesfully"
# fi

# message_info "Running docker compose"
# echo -e "\tdocker-compose -f "$traefik_path/docker-compose.yml" up --detach"
# docker-compose -f "$traefik_path/docker-compose.yml" up --detach




